import Head from "next/head"
import { Geist, Geist_Mono } from 'next/font/google'
import Link from "next/link"
import styles from '@/styles/Home.module.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export default function RootLayout({
    metaTitle,
    children,
     } : { 
        metaTitle ?: string
        children: React.ReactNode
        }) {
    return (
        <>
            <Head>
                <title>{`Obol App - ${metaTitle || ''}`}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className={`${geistSans.variable} ${geistMono.variable} flex flex-col min-h-screen`}>

           <header className="bg-black text-white p-4">
                <div className="container mx-auto flex justify-between items-center">
                    <h1 className="text-xl font-bold">
                        
                        <Link href="/">Obol App</Link>
                    </h1>
                    <ul className="flex space-x-4">
                        <li>
                            <Link href='/' className="hover:text-pink-500 transition-colors duration-200">Home</Link>
                        </li>
                        <li>
                            <Link href='/about' className="hover:text-pink-500 transition-colors duration-200">About</Link>
                        </li>
                    </ul>
                </div>
            </header>


            <main className="flex-1 container mx-auto p-4">
                {children}
            </main>

            <footer className="bg-gradient-to-r from-pink-500 via-pink-400 to-pink-200 text-white p-4 text-center py-10">
            <h1 className="text-2xl font-bold mb-4">Contact Me</h1>
            <ul className="flex flex-col items-center space-y-2">
                <li>
                <a href="mailto:putrisafa1394@gmail.com"
                    className="hover:text-black transition-colors duration-200">
                    Email: putrisafa1394@gmail.com
                </a>
                </li>
                <li>
                <a href="https://linkedin.com/in/nabiilahputri"
                    target="_blank"
                    rel="noopener noreferrer"
                    className="hover:text-black transition-colors duration-200">
                    LinkedIn: linkedin.com/in/nabiilahputri
                </a>
                </li>
            </ul>
            </footer>


            <footer className="bg-black text-white text-center py-4">
                <p>&copy; {new Date().getFullYear()} Obol App. All rights reserved.</p>
            </footer>
            </div>
        </>
    )
}