import Head from "next/head"
import { Geist, Geist_Mono } from 'next/font/google'
import Link from "next/link"
import styles from '@/styles/Home.module.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export default function RootLayout({
    metaTitle,
    children,
     } : { 
        metaTitle ?: string
        children: React.ReactNode
        }) {
    return (
        <>
            <Head>
                <title>{`Obol App - ${metaTitle || ''}`}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className={`${geistSans.variable} ${geistMono.variable} flex flex-col min-h-screen`}>

           <header className="bg-black text-white p-4 sticky top-0 z-50">
                <div className="container mx-auto flex justify-between items-center">
                    <h1 className="text-3xl font-bold">
                        <Link href="/">YARNIT</Link>
                    </h1>
                    <ul className="flex font-semibold space-x-4">
                        <li>
                            <Link href='/' className="hover:text-pink-500 transition-colors duration-200">Home</Link>
                        </li>
                        <li>
                            <Link href='/about' className="hover:text-pink-500 transition-colors duration-200">About</Link>
                        </li>
                        <li>
                            <Link href='/' className="hover:text-pink-500 transition-colors duration-200">Shop Yarn</Link>
                        </li>
                        <li>
                            <Link href='/' className="hover:text-pink-500 transition-colors duration-200">Find Pattern</Link>
                        </li>
                    </ul>
                </div>
            </header>

            <main className="flex-1">
                {children}
            </main>

            <footer className="bg-black text-white p-4 py-15">
                <h1 className="text-5xl text-center font-bold mb-4 px-4">YARNIT</h1>
                {/* <div className="flex items-start px-30 space-x-8">
                    <ul className="flex flex-col space-y-2">
                        <li className="hover:text-pink-500 transition-colors duration-200">
                            Contact Us
                        </li>
                        <li className="hover:text-pink-500 transition-colors duration-200">
                            FAQs
                        </li>
                    </ul>
                </div> */}
            </footer>


            <footer className="bg-black text-white text-center py-2">
                <p>&copy; {new Date().getFullYear()} by Nabiilah Putri Safa. All rights reserved.</p>
            </footer>
            </div>
        </>
    )
}